### ISSUE TITLE
why does this project use bootstrap please?

### ISSUE THREAD

**Issue by videni** [mdbootstrap/Tailwind-Elements#1040]
Sorry for this silly question, I am new to this project, I can see this project has a bootstrap dependency, on the surface, this project should be a replacement of bootstrap. can anyone explain why it uses bootstrap please？

**Comment by filipkappa** [comment]
This project doesn't use Bootstrap, it just recreates some of the bootstrap components using Tailwind.

**Comment by videni** [comment]
@filipkappa ， still confused,  since it recreates some of the bootstrap components using Tailwind, why has direct dependency on bootstrap please？ what  bootstrap features are  dependent ?

**Comment by filipkappa** [comment]
Our bad. We removed the dependency, it shouldn't be there in the first place. Apologies for the confusion.

**Comment by tmikaeld** [comment]
@filipkappa It's still there and required for mega menus to work, please fix.
